name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12, 14, 16]

    steps:
      - name: Check out repo
        uses: actions/checkout@v4.1.1

      - name: Install node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node }}

      - run: npm ci

      - run: npm test

      - run: npm run build

      - run: npm run package
